In [2]:
import numpy as np

In [3]:
n1 = np.array([1,2,3,4])
print(n1)
print(type(n1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
n1

array([1, 2, 3, 4])

In [5]:
x=[]
len(dir(x))

47

In [6]:
len(dir(n1))

165

In [7]:
n1.shape

(4,)

In [8]:
n2=np.array([[1,2,3],[2,3,5]])
print(n2)
print(n2.shape)

[[1 2 3]
 [2 3 5]]
(2, 3)


creating matrix  
- arange  
- linspace  
- random.rand  
- random.randn 
- random.randint 
- eye 
- ones 
- zeros 

In [9]:
 x= np.arange(-10,10,.2)
x.shape

(100,)

In [10]:
y = np.linspace(1,5,25)
print(y)
y.shape

[1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.         2.16666667 2.33333333 2.5        2.66666667 2.83333333
 3.         3.16666667 3.33333333 3.5        3.66666667 3.83333333
 4.         4.16666667 4.33333333 4.5        4.66666667 4.83333333
 5.        ]


(25,)

In [11]:
np.random.rand(3,3)

array([[0.531336  , 0.1622138 , 0.31703562],
       [0.04929043, 0.28611603, 0.95488303],
       [0.30967799, 0.95404098, 0.62537611]])

In [12]:
np.random.randn(10)

array([-1.58350186, -1.4410301 , -1.07671889,  0.65647408, -1.87512018,
       -0.32251396, -0.0599398 , -0.3742899 , -1.79444078,  0.62989308])

In [13]:
(np.random.randint(1,1000,(5,5)))

array([[481, 296, 326, 505, 601],
       [918, 776, 936, 942, 797],
       [552, 716,  13, 566,  90],
       [175, 415, 532, 941, 580],
       [759, 447, 775, 153, 976]])

In [14]:
x=np.random. randint(1,11,(3,2))
y=np.random. randint(1,10,(3,2))
print(x)
print(y)

[[2 1]
 [4 4]
 [3 7]]
[[4 8]
 [3 2]
 [5 4]]


In [15]:
x+5

array([[ 7,  6],
       [ 9,  9],
       [ 8, 12]])

In [16]:
x*5

array([[10,  5],
       [20, 20],
       [15, 35]])

In [17]:
x+y # matrix addition

array([[ 6,  9],
       [ 7,  6],
       [ 8, 11]])

In [18]:
x * y

array([[ 8,  8],
       [12,  8],
       [15, 28]])

In [19]:
y.T

array([[4, 3, 5],
       [8, 2, 4]])

In [20]:
y.dot(y.T)

array([[80, 28, 52],
       [28, 13, 23],
       [52, 23, 41]])

In [21]:
np.sin(x)

array([[ 0.90929743,  0.84147098],
       [-0.7568025 , -0.7568025 ],
       [ 0.14112001,  0.6569866 ]])

In [22]:
print(x.sum())
print(x.mean())
print(x.std())
print(x.min())
print(x.max())

21
3.5
1.8929694486000912
1
7


In [24]:
a = np.linspace(0,5,50)
print(a.shape)
a2=a.reshape(10,5)
print(a2)
print(a2.shape)


(50,)
[[0.         0.10204082 0.20408163 0.30612245 0.40816327]
 [0.51020408 0.6122449  0.71428571 0.81632653 0.91836735]
 [1.02040816 1.12244898 1.2244898  1.32653061 1.42857143]
 [1.53061224 1.63265306 1.73469388 1.83673469 1.93877551]
 [2.04081633 2.14285714 2.24489796 2.34693878 2.44897959]
 [2.55102041 2.65306122 2.75510204 2.85714286 2.95918367]
 [3.06122449 3.16326531 3.26530612 3.36734694 3.46938776]
 [3.57142857 3.67346939 3.7755102  3.87755102 3.97959184]
 [4.08163265 4.18367347 4.28571429 4.3877551  4.48979592]
 [4.59183673 4.69387755 4.79591837 4.89795918 5.        ]]
(10, 5)


In [26]:
a2.reshape(5,5,2)

array([[[0.        , 0.10204082],
        [0.20408163, 0.30612245],
        [0.40816327, 0.51020408],
        [0.6122449 , 0.71428571],
        [0.81632653, 0.91836735]],

       [[1.02040816, 1.12244898],
        [1.2244898 , 1.32653061],
        [1.42857143, 1.53061224],
        [1.63265306, 1.73469388],
        [1.83673469, 1.93877551]],

       [[2.04081633, 2.14285714],
        [2.24489796, 2.34693878],
        [2.44897959, 2.55102041],
        [2.65306122, 2.75510204],
        [2.85714286, 2.95918367]],

       [[3.06122449, 3.16326531],
        [3.26530612, 3.36734694],
        [3.46938776, 3.57142857],
        [3.67346939, 3.7755102 ],
        [3.87755102, 3.97959184]],

       [[4.08163265, 4.18367347],
        [4.28571429, 4.3877551 ],
        [4.48979592, 4.59183673],
        [4.69387755, 4.79591837],
        [4.89795918, 5.        ]]])

In [27]:
a2.reshape(50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [31]:
m=np.random.randint(1,10,(10,10))
print(m)

[[3 2 6 5 9 1 8 5 4 5]
 [2 8 8 9 8 5 4 3 1 2]
 [1 2 7 4 9 7 4 8 8 9]
 [4 4 3 9 3 9 5 8 5 8]
 [9 6 5 5 7 3 7 9 3 4]
 [1 6 4 5 6 5 8 5 5 7]
 [9 8 6 8 3 8 7 5 3 2]
 [3 8 1 6 7 1 9 2 2 5]
 [8 1 1 6 9 5 7 7 6 9]
 [8 8 4 6 9 6 1 3 7 7]]


In [33]:
print(m[0,0]) #numpy column wise slicing krta haiii(firt row first column)
print(m[0,-1]) # first row, last column
print(m[-1,0])#last row first column
print(m[-1,-1]) # last row last column


3
5
8
7


In [34]:
print(m[0])#first row
print(m[1])#second row
print(m[-1])#last row
print(m[:3])#first three row
print(m[-3:])#last 3 row

[3 2 6 5 9 1 8 5 4 5]
[2 8 8 9 8 5 4 3 1 2]
[8 8 4 6 9 6 1 3 7 7]
[[3 2 6 5 9 1 8 5 4 5]
 [2 8 8 9 8 5 4 3 1 2]
 [1 2 7 4 9 7 4 8 8 9]]
[[3 8 1 6 7 1 9 2 2 5]
 [8 1 1 6 9 5 7 7 6 9]
 [8 8 4 6 9 6 1 3 7 7]]


In [39]:
m[:,0]# 1 st coloumn
m[:,-1]# last st coloumn
m[:,:3]# first 3  coloumn
m[:,-3:]# last 3 coloumn


array([[5, 4, 5],
       [3, 1, 2],
       [8, 8, 9],
       [8, 5, 8],
       [9, 3, 4],
       [5, 5, 7],
       [5, 3, 2],
       [2, 2, 5],
       [7, 6, 9],
       [3, 7, 7]])

In [40]:
print(m[:,[0,2,3,5]])

[[3 6 5 1]
 [2 8 9 5]
 [1 7 4 7]
 [4 3 9 9]
 [9 5 5 3]
 [1 4 5 5]
 [9 6 8 8]
 [3 1 6 1]
 [8 1 6 5]
 [8 4 6 6]]


# Filtering 


In [41]:
m

array([[3, 2, 6, 5, 9, 1, 8, 5, 4, 5],
       [2, 8, 8, 9, 8, 5, 4, 3, 1, 2],
       [1, 2, 7, 4, 9, 7, 4, 8, 8, 9],
       [4, 4, 3, 9, 3, 9, 5, 8, 5, 8],
       [9, 6, 5, 5, 7, 3, 7, 9, 3, 4],
       [1, 6, 4, 5, 6, 5, 8, 5, 5, 7],
       [9, 8, 6, 8, 3, 8, 7, 5, 3, 2],
       [3, 8, 1, 6, 7, 1, 9, 2, 2, 5],
       [8, 1, 1, 6, 9, 5, 7, 7, 6, 9],
       [8, 8, 4, 6, 9, 6, 1, 3, 7, 7]])

In [42]:
m<5 # boolean filter

array([[ True,  True, False, False, False,  True, False, False,  True,
        False],
       [ True, False, False, False, False, False,  True,  True,  True,
         True],
       [ True,  True, False,  True, False, False,  True, False, False,
        False],
       [ True,  True,  True, False,  True, False, False, False, False,
        False],
       [False, False, False, False, False,  True, False, False,  True,
         True],
       [ True, False,  True, False, False, False, False, False, False,
        False],
       [False, False, False, False,  True, False, False, False,  True,
         True],
       [ True, False,  True, False, False,  True, False,  True,  True,
        False],
       [False,  True,  True, False, False, False, False, False, False,
        False],
       [False, False,  True, False, False, False,  True,  True, False,
        False]])

In [43]:
m[m<5]

array([3, 2, 1, 4, 2, 4, 3, 1, 2, 1, 2, 4, 4, 4, 4, 3, 3, 3, 3, 4, 1, 4,
       3, 3, 2, 3, 1, 1, 2, 2, 1, 1, 4, 1, 3])

In [52]:
m[m>3].sum

<function ndarray.sum>

In [47]:
m[(m>=3 )&( m <=6)]

array([3, 6, 5, 5, 4, 5, 5, 4, 3, 4, 4, 4, 4, 3, 3, 5, 5, 6, 5, 5, 3, 3,
       4, 6, 4, 5, 6, 5, 5, 5, 6, 3, 5, 3, 3, 6, 5, 6, 5, 6, 4, 6, 6, 3])