In [1]:
import numpy as np

In [2]:
n1 = np.array([1,2,3,4])
print(n1)
print(type(n1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
n1

array([1, 2, 3, 4])

In [5]:
x=[]
len(dir(x))

47

In [6]:
len(dir(n1))

165

In [7]:
n1.shape

(4,)

In [8]:
n2=np.array([[1,2,3],[2,3,5]])
print(n2)
print(n2.shape)

[[1 2 3]
 [2 3 5]]
(2, 3)


creating matrix  
- arange  
- linspace  
- random.rand  
- random.randn 
- random.randint 
- eye 
- ones 
- zeros 

In [12]:
 x= np.arange(-10,10,.2)
x.shape

(100,)

In [16]:
y = np.linspace(1,5,25)
print(y)
y.shape

[1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.         2.16666667 2.33333333 2.5        2.66666667 2.83333333
 3.         3.16666667 3.33333333 3.5        3.66666667 3.83333333
 4.         4.16666667 4.33333333 4.5        4.66666667 4.83333333
 5.        ]


(25,)

In [19]:
np.random.rand(3,3)

array([[0.41625754, 0.93460868, 0.24672662],
       [0.80101555, 0.30993011, 0.68669993],
       [0.36170511, 0.79747107, 0.66353363]])

In [20]:
np.random.randn(10)

array([-0.69671801, -0.93541617,  0.15071293, -0.6434092 , -0.50093748,
       -0.00691642, -0.5101908 , -0.74415315,  0.29477461, -0.93970624])

In [23]:
(np.random.randint(1,1000,(5,5)))

array([[347, 637, 154, 340, 674],
       [566, 482, 876, 842,  75],
       [280, 269,  61, 905,  88],
       [226, 913, 102, 718,  49],
       [570, 356, 952, 759, 199]])

In [25]:
x=np.random. randint(1,11,(3,2))
y=np.random. randint(1,10,(3,2))
print(x)
print(y)

[[7 9]
 [1 5]
 [4 6]]
[[4 6]
 [3 2]
 [8 9]]


In [26]:
x+5

array([[12, 14],
       [ 6, 10],
       [ 9, 11]])

In [27]:
x*5

array([[35, 45],
       [ 5, 25],
       [20, 30]])

In [28]:
x+y # matrix addition

array([[11, 15],
       [ 4,  7],
       [12, 15]])

In [29]:
x * y

array([[28, 54],
       [ 3, 10],
       [32, 54]])

In [33]:
y.T

array([[4, 3, 8],
       [6, 2, 9]])

In [37]:
y.dot(y.T)

array([[ 52,  24,  86],
       [ 24,  13,  42],
       [ 86,  42, 145]])

In [35]:
np.sin(x)

array([[ 0.6569866 ,  0.41211849],
       [ 0.84147098, -0.95892427],
       [-0.7568025 , -0.2794155 ]])

In [40]:
print(x.sum())
print(x.mean())
print(x.std())
print(x.min())
print(x.max())

32
5.333333333333333
2.494438257849294
1
9
